photos/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.decorators import login_required

app_name='photos'

urlpatterns = [
    # login_required 는 함수를 장식하는 장식자이다. 그런데 Class based View는 클래스이기때문에 장식할 수 없다.
    # 따라서 여기서 as_view()를 할때 한다.
    #url(r'^create/$', login_required(views.PhotoCreate.as_view()), name='create_photo'),
    url(r'^create/$', views.create_photo, name='create_photo'),
    # 참고로 views에서 login_required(views.PhotoCreate.as_view()) 를 변수에 할당해 놓고 그걸 참조하면, urls에서 함수형view인지 클래스형 view인지에 무관하게
    # 똑같은 표현으로 사용할 수 있다.

    url(r'^delete/(?P<pk>[0-9]+)/$', views.delete_photo, name='delete_photo'),
    url(r'^view_photo/(?P<pk>[0-9]+)/$', views.view_photo, name='view_photo'),
    url(r'^(?P<pk>[0-9]+)/comment/create/$', views.create_comment, name='create_comment'),
    url(r'^(?P<pk>[0-9]+)/comment/delete/$', views.delete_comment, name='delete_comment'),
    url(r'^list_photo/$', views.list_photo, name='list_photo'),
]

pystagram/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^login/', login, name='login_url', kwargs={'template_name' : 'login.html'}),
    url(r'^logout/', logout, name='logout_url', kwargs={'next_page' : '/login'}),
    url(r'^photos/', include('photos.urls')),
    url(r'^admin/', admin.site.urls),
]

# static 파일들을 경로를 위함..
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/models.py
from django.db import models
from django.conf import settings
from django.core.urlresolvers import reverse_lazy

# Create your models here.
class Photo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=300)
    content = models.TextField()
    image = models.ImageField(upload_to='%Y/%m/%d', null=True, blank=True)
    description = models.TextField(max_length=500,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse_lazy('photos:view_photo', kwargs= {'pk':self.pk})
        # return '/photos/{}/'.format(self.pk)

class Comment(models.Model):
    photo = models.ForeignKey(Photo, null=True)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{}: {}'.format(self.pk, self.content)

photos/forms.py
from django import forms
from .models import Photo

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ('title', 'content', 'image', 'description',)

photos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.edit import CreateView
from .models import Photo, Comment
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage

class PhotoCreate(CreateView):
    model = Photo
    fields = ('title', 'content', 'image', 'description', )
    template_name = 'create_photo.html'

    # 유효성 검사 이후에 호출되는 함수.
    def form_valid(self, form):
        new_photo = form.save(commit=False)
        new_photo.user = self.request.user
        new_photo.save()

        return super(PhotoCreate, self).form_valid(form)

create_photo = login_required(PhotoCreate.as_view())

@login_required
def delete_photo(request, pk):
    photo = get_object_or_404(Photo, pk=pk)

    if request.method == 'POST':
        photo.delete()
        return redirect('photos:list_photo')

    return render(request, 'delete_photo.html', {'photo' : photo})

def view_photo(request, pk):
    photo = get_object_or_404(Photo, pk=pk)

    ctx = {
        'photo' : photo,
        'comments' : Comment.objects.filter(photo=photo)
    }

    return render(request, 'detail.html', ctx)

@login_required
def create_comment(request, pk):
    photo = get_object_or_404(Photo, pk=pk)
    comment = request.POST.get('comment')

    if request.method == 'POST':
        new_comment = Comment()
        new_comment.photo = photo
        new_comment.content = comment
        new_comment.save()

    return redirect(reverse('photos:view_photo', kwargs={'pk' : photo.pk}))

@login_required
def delete_comment(request, pk):
    if request.method == 'POST':
        comment_pk = request.POST.get('comment_id')
        comment = get_object_or_404(Comment, pk=comment_pk)
        comment.delete()

    return redirect(reverse('photos:view_photo', kwargs={'pk': pk}))

def list_photo(request):
    per_page = 5
    page = request.GET.get('page', 1)

    photos = Photo.objects.all()

    pg = Paginator(photos, per_page)
    try:
        # Paginator가 page값에 대한 예외처리를 알아서 하지는 않는다. 예외처리는 별도로 한다.
        contents = pg.page(page)
    except PageNotAnInteger:
        contents = pg.page(1)
    except EmptyPage:
        contents = []

    ctx = {
        # template에 전달되는 객체는 page 객체이다. page 객체를 이용해 UI 필요한 여러 편리한 기능을 사용할 수 있다.
        'photos' : contents,
    }

    return render(request, 'list.html', ctx)

photos/templates/create_photo.html
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}

    {{ form.as_p }}

    <p>
        <button type="submit">저장</button>
    </p>
</form>

photos/templates/delete_photo.html
{% extends 'layout.html' %}

{% block page_title %}{{ photo.title }} - 게시물 삭제{% endblock %}

{% block body %}

    <form method="POST" action="">
        {% csrf_token %}

        <p>삭제 하시겠습니까?</p>
        <p>
            <button type="submit">삭제</button>
        </p>
    </form>

{% endblock %}

photos/templates/detail.html
{% extends 'layout.html' %}

{% block page_title %}사진 보기{% endblock %}

{% block body %}
    <p> {{ photo.title }} </p>
    <p> {{ photo.content }} </p>
    <div> {{ photo.description }} </div>

    <p> {{ photo.created_at }} </p>
    <p> {{ photo.updated_at }} </p>

    {% if photo.image %}
        <p><img src="{{ photo.image.url }}" /> </p>
    {% endif %}



    <h3>댓글</h3>
    {% for comment in comments %}
        <div> {{ comment.content }} </div>
        <form method="POST" action="{% url 'photos:delete_comment' pk=photo.pk %}">
            {% csrf_token %}
            <input type="hidden" name="comment_id" value="{{ comment.pk }}"> <br>
            <button type="submit">댓글삭제</button>
        </form>
    {% endfor %}

    <P><a href="{% url 'photos:delete_photo' pk=photo.pk%}">사진 삭제</a></P>
    <P><a href="{% url 'photos:list_photo' %}">사진 목록</a></P>

    <form method="POST" action="{% url 'photos:create_comment' pk=photo.pk %}">
        {% csrf_token %}
        <p>
            <textarea name="comment"></textarea>
        </p>
        <button type="submit">저장</button>
    </form>

{% endblock %}

photos/templates/list.html
{% extends 'layout.html' %}
{% load bootstrap3 %}

{% block page_title %}게시물 목록{% endblock %}

{% block body %}
    <h1>게시물 목록</h1>

    {% for photo in photos %}
        <p><a href="{% url 'photos:view_photo' pk=photo.pk %}">{{ post.title }}</a></p>

        {{ photo.title }}
        <!-- post에 값이 없는 경우 아래의 empty가 실행된다. -->
        {% empty %}
        <p>게시물이 없습니다.</p>

    {% endfor %}

{% bootstrap_pagination photos %}

{% comment %}
    {% if photos.has_previous %}
        <a href="?page={{ photos.previous_page_number }}">이전</a>
    {% endif %}

    {{ photos.number }} / {{ photos.paginator.num_pages}}

    {% if photos.has_next %}
        <a href="?page={{ photos.next_page_number }}">다음</a>
    {% endif %}
{% endcomment %}

    <p>
        <a href="{% url 'photos:create_photo' %}">새 글 쓰기</a>
    </p>

{% endblock %}